In [3]:
import numpy as np

In [7]:
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [9]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
l=range(100)
%timeit [i**2 for i in l]

13.4 μs ± 354 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [23]:
a=np.arange(100)
%timeit a**2

1.53 μs ± 37.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Creating Arrays

In [ ]:
a=np.array([1,2,3,4]) #one dimensional array

In [26]:
print(a.ndim)

1


In [32]:
b = np.array([[1,2,3],[4,5,6]])  #two dimensional array

In [34]:
print(b.ndim)

2


In [36]:
print(b)

[[1 2 3]
 [4 5 6]]


In [52]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])  #three dimensional array

In [54]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [56]:
print(c.ndim)

3


In [66]:
print(a.shape)

(100,)


In [62]:
print(b.shape)

(2, 3)


In [68]:
print(c.shape)

(2, 2, 2)


# Functions For Creating Array

In [71]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [73]:
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [75]:
#using linspace
a = np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [79]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [81]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [85]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [89]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [91]:
a=np.eye(3,4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [95]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [97]:
print(np.diag(a))

[1 2 3 4]


# Basic Data Types

In [100]:
a = np.arange(10)
print(a.dtype)

int32


In [110]:
a = np.arange(10,dtype="float")
print(a.dtype)

float64


In [106]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


# Other Datatypes

In [113]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [115]:
a=np.array([True,False])
print(a.dtype)

bool


In [119]:
a=np.array(['Raju'])
print(a.dtype)    #Unicode string type

<U4


# Indexing and Slicing

In [124]:
a=np.arange(10)
print(a[5])

5


In [126]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [128]:
a[2,1]=5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


# Slicing

In [131]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [133]:
print(a[1:8:2])

[1 3 5 7]


In [137]:
a=np.arange(10)
(a[5:])=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

# Copies and Viewing

In [156]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [158]:
print(np.shares_memory(a,b))

True


In [160]:
b[0]=10
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [164]:
a=np.arange(10)
b=a[::2].copy()   #force a copy
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [166]:
print(np.shares_memory(a,b))

False


In [168]:
b[0]=10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


# Random Number Generator

In [171]:
a=np.random.randint(0,20,15)
print(a)

[ 0 17 18  5 10 14  9  2  0 17 17  5  1 11  4]


In [173]:
mask=(a%2==0)

In [175]:
mask_a=a[mask]
print(mask_a)

[ 0 18 10 14  2  0  4]


In [177]:
a[mask]=-1
print(a)

[-1 17 -1  5 -1 -1  9 -1 -1 17 17  5  1 11 -1]


# Day-6

# Element wise Operations

## 1.Basic Operations

In [14]:
import numpy as np
a=np.array([1,2,3,4])
print(a+1)  #add + 1

[2 3 4 5]


In [18]:
import numpy as np
a=np.array([1,2,3,4])
print(a+2) 

[3 4 5 6]


In [16]:
print(a**2)  #squares

[ 1  4  9 16]


# All Arthimetic operates Elementwise

In [24]:
b=np.ones(4)+1 #[2 2 2 2]
print("a= ",a)
print("b= ",b)

a=  [1 2 3 4]
b=  [2. 2. 2. 2.]


In [26]:
print(a*b)

[2. 4. 6. 8.]


In [28]:
print(a-b)

[-1.  0.  1.  2.]


In [30]:
print(a+b)

[3. 4. 5. 6.]


In [32]:
#matrix multiplication
c=np.diag([1,2,3,4])
print(c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [34]:
print(c*c)
print("********************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
********************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


# Comparision Operators

In [37]:
a=np.array([1,2,3,4])
b=np.array([5,2,7,4])
print(a==b)

[False  True False  True]


In [39]:
print(a<b)

[ True False  True False]


In [41]:
print(a>b)

[False False False False]


In [43]:
print(a<=b)

[ True  True  True  True]


In [45]:
print(a>=b)

[False  True False  True]


In [51]:
# Array Wise comparision
a=np.array([1,2,3,4])
b=np.array([5,2,7,4])
c=np.array([1,2,3,4])
print(np.array_equal(a,b))

False


In [53]:
print(np.array_equal(a,c))

True


# Logical Operators

In [56]:
a=np.array([1,0,1,0],dtype="bool")
b=np.array([1,1,0,0],dtype="bool")

In [58]:
print(np.logical_or(a,b))

[ True  True  True False]


In [60]:
print(np.logical_and(a,b))

[ True False False False]


In [62]:
print(np.logical_not(a,b))

[False  True False  True]


# Trigonometry/ Transcendental Functions

In [65]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [71]:
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128]


In [73]:
np.log(a)

C:\Users\raidu\AppData\Local\Temp\ipykernel_5472\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [75]:
print(np.exp(a))

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


# Basic Reductions

In [78]:
x=np.array([1,2,3,4])
print(np.sum(x))

10


In [80]:
x=np.array([[1,2],[1,2]])
print(x)

[[1 2]
 [1 2]]


In [82]:
x.sum(axis=0) #column dimesions

array([2, 4])

In [90]:
x.sum(axis=1) #row dimesions

array([3, 3])

# Day-7

# Pandas

In [35]:
import pandas as pd

# Day-8

## Statistics

In [43]:
df= pd.read_csv(r"C:\Users\raidu\Downloads\weather_data.csv")
df

DATE       CITy  TEMPERATURE  HUMIDITY_% CONDITION
0   01-01-1900  HYDERABAD           28          60     SUNNY
1   02-01-1990  HYDERABAD           29          52     SUNNY
2   03-01-1990  HYDERABAD           30          58    CLOUDY
3   04-01-1990  HYDERABAD           31          55    CLOUDY
4   05-01-1990  HYDERABAD           32          57    CLOUDY
5   06-01-1990  HYDERABAD           33          55     SUNNY
6   07-01-1990  BANGALORE           34          54     SUNNY
7   08-01-1990  BANGALORE           35          55     SUNNY
8   09-01-1990  BANGALORE           36          58     SUNNY
9   10-01-1990  BANGALORE           37          59     SUNNY
10  11-01-1990  BANGALORE           38          60    CLOUDY
11  12-01-1990  BANGALORE           39          61    CLOUDY

In [77]:
df['TEMPERATURE'].max()

39

In [79]:
df['TEMPERATURE'].min()

28

In [81]:
df['TEMPERATURE'].mean()

33.5

In [83]:
df['TEMPERATURE'].describe()

count    12.000000
mean     33.500000
std       3.605551
min      28.000000
25%      30.750000
50%      33.500000
75%      36.250000
max      39.000000
Name: TEMPERATURE, dtype: float64

In [67]:
df[df.TEMPERATURE==df.TEMPERATURE.max()]

DATE       CITy  TEMPERATURE  HUMIDITY_% CONDITION
11  12-01-1990  BANGALORE           39          61    CLOUDY

In [69]:
df.CITy[df.TEMPERATURE==df.TEMPERATURE.max()]

11    BANGALORE
Name: CITy, dtype: object

In [71]:
df.count()

DATE           12
CITy           12
TEMPERATURE    12
HUMIDITY_%     12
CONDITION      12
dtype: int64

In [87]:
df["CITy"].nunique()

2

In [89]:
df["CITy"].value_counts()

CITy
HYDERABAD    6
BANGALORE    6
Name: count, dtype: int64

# String Cleaning

In [101]:
df

DATE       CITy  TEMPERATURE  HUMIDITY_% CONDITION
0   01-01-1900  HYDERABAD           28          60     SUNNY
1   02-01-1990  HYDERABAD           29          52     SUNNY
2   03-01-1990  HYDERABAD           30          58    CLOUDY
3   04-01-1990  HYDERABAD           31          55    CLOUDY
4   05-01-1990  HYDERABAD           32          57    CLOUDY
5   06-01-1990  HYDERABAD           33          55     SUNNY
6   07-01-1990  BANGALORE           34          54     SUNNY
7   08-01-1990  BANGALORE           35          55     SUNNY
8   09-01-1990  BANGALORE           36          58     SUNNY
9   10-01-1990  BANGALORE           37          59     SUNNY
10  11-01-1990  BANGALORE           38          60    CLOUDY
11  12-01-1990  BANGALORE           39          61    CLOUDY

In [105]:
df["CITy"]=df["CITy"].str.lower()
df

DATE       CITy  TEMPERATURE  HUMIDITY_% CONDITION
0   01-01-1900  hyderabad           28          60     SUNNY
1   02-01-1990  hyderabad           29          52     SUNNY
2   03-01-1990  hyderabad           30          58    CLOUDY
3   04-01-1990  hyderabad           31          55    CLOUDY
4   05-01-1990  hyderabad           32          57    CLOUDY
5   06-01-1990  hyderabad           33          55     SUNNY
6   07-01-1990  bangalore           34          54     SUNNY
7   08-01-1990  bangalore           35          55     SUNNY
8   09-01-1990  bangalore           36          58     SUNNY
9   10-01-1990  bangalore           37          59     SUNNY
10  11-01-1990  bangalore           38          60    CLOUDY
11  12-01-1990  bangalore           39          61    CLOUDY

In [107]:
df["CITy"]=df["CITy"].str.upper()
df

DATE       CITy  TEMPERATURE  HUMIDITY_% CONDITION
0   01-01-1900  HYDERABAD           28          60     SUNNY
1   02-01-1990  HYDERABAD           29          52     SUNNY
2   03-01-1990  HYDERABAD           30          58    CLOUDY
3   04-01-1990  HYDERABAD           31          55    CLOUDY
4   05-01-1990  HYDERABAD           32          57    CLOUDY
5   06-01-1990  HYDERABAD           33          55     SUNNY
6   07-01-1990  BANGALORE           34          54     SUNNY
7   08-01-1990  BANGALORE           35          55     SUNNY
8   09-01-1990  BANGALORE           36          58     SUNNY
9   10-01-1990  BANGALORE           37          59     SUNNY
10  11-01-1990  BANGALORE           38          60    CLOUDY
11  12-01-1990  BANGALORE           39          61    CLOUDY

In [109]:
df["CITy"]=df["CITy"].str.replace("HYDERABAD","CHENNAI")
df

DATE       CITy  TEMPERATURE  HUMIDITY_% CONDITION
0   01-01-1900    CHENNAI           28          60     SUNNY
1   02-01-1990    CHENNAI           29          52     SUNNY
2   03-01-1990    CHENNAI           30          58    CLOUDY
3   04-01-1990    CHENNAI           31          55    CLOUDY
4   05-01-1990    CHENNAI           32          57    CLOUDY
5   06-01-1990    CHENNAI           33          55     SUNNY
6   07-01-1990  BANGALORE           34          54     SUNNY
7   08-01-1990  BANGALORE           35          55     SUNNY
8   09-01-1990  BANGALORE           36          58     SUNNY
9   10-01-1990  BANGALORE           37          59     SUNNY
10  11-01-1990  BANGALORE           38          60    CLOUDY
11  12-01-1990  BANGALORE           39          61    CLOUDY

## Concate Data Frames

In [114]:
india_weather=pd.DataFrame({
    "City" : ["mumbai","bangalore","hyderabad"],
    "Temperature":[32,45,35]
})
india_weather
    

City  Temperature
0     mumbai           32
1  bangalore           45
2  hyderabad           35

In [122]:
US_weather=pd.DataFrame({
    "City" : ["New york","Chicago","orlando"],
        "Temperature":[32,45,35]
})
US_weather
    

City  Temperature
0  New york           32
1   Chicago           45
2   orlando           35

In [124]:
df=pd.concat([india_weather,US_weather])
df

City  Temperature
0     mumbai           32
1  bangalore           45
2  hyderabad           35
0   New york           32
1    Chicago           45
2    orlando           35

In [126]:
df=pd.concat([india_weather,US_weather],ignore_index=True)
df

City  Temperature
0     mumbai           32
1  bangalore           45
2  hyderabad           35
3   New york           32
4    Chicago           45
5    orlando           35

In [128]:
df=pd.concat([india_weather,US_weather],axis=1)
df

City  Temperature      City  Temperature
0     mumbai           32  New york           32
1  bangalore           45   Chicago           45
2  hyderabad           35   orlando           35

## Merge DataFrames

In [131]:
temp_df=pd.DataFrame({
    "city":["Hydderbad","Visakapatnam","Chennai","Bangalore"],
    "temperature":[32,45,30,34]
})
temp_df

city  temperature
0     Hydderbad           32
1  Visakapatnam           45
2       Chennai           30
3     Bangalore           34

In [151]:
humidity_df=pd.DataFrame({
    "city":["Hydderbad","Kakinada","Chennai","Bangalore"],
    "humidity":[32,45,30,34]
})
humidity_df

city  humidity
0  Hydderbad        32
1   Kakinada        45
2    Chennai        30
3  Bangalore        34

In [153]:
df=pd.merge(temp_df,humidity_df,on="city")
df

city  temperature  humidity
0  Hydderbad           32        32
1    Chennai           30        30
2  Bangalore           34        34

In [161]:
df=pd.merge(temp_df,humidity_df,on="city",how="outer")
df

city  temperature  humidity
0     Bangalore         34.0      34.0
1       Chennai         30.0      30.0
2     Hydderbad         32.0      32.0
3      Kakinada          NaN      45.0
4  Visakapatnam         45.0       NaN

In [163]:
df.isnull() #To find null values /missing values

city  temperature  humidity
0  False        False     False
1  False        False     False
2  False        False     False
3  False         True     False
4  False        False      True

In [165]:
df.isnull().sum()

city           0
temperature    1
humidity       1
dtype: int64

In [169]:
df['temperature']=df['temperature'].fillna(df.temperature.min())
df

city  temperature  humidity
0     Bangalore         34.0      34.0
1       Chennai         30.0      30.0
2     Hydderbad         32.0      32.0
3      Kakinada         30.0      45.0
4  Visakapatnam         45.0       NaN

# Day-9

# Co-variance


In [13]:
import pandas as pd

In [15]:
df=pd.read_csv(r"C:\Users\raidu\Downloads\study_marks.csv")
df

Study_Hours  Marks
0          2.9   27.0
1          5.8   61.0
2          4.7   45.0
3          4.0   38.0
4          1.8   19.0
5          1.8    8.0
6          1.3    4.0
7          5.3   50.0
8          4.0   35.0
9          4.5   47.0

In [25]:
df.cov()  # To find the covariance

Study_Hours       Marks
Study_Hours     2.481000   28.906667
Marks          28.906667  348.711111

In [27]:
df.corr() # To find the correlation

Study_Hours    Marks
Study_Hours      1.00000  0.98277
Marks            0.98277  1.00000

In [39]:
df=pd.read_csv(r"C:\Users\raidu\Downloads\temp_icecream_sales.csv")
df

Temperature  IceCream_Sales
0           20             200
1           22             220
2           24             250
3           26             270
4           28             300
5           30             320
6           32             350
7           34             370
8           36             400
9           38             420

In [47]:
df.cov()

Temperature  IceCream_Sales
Temperature       36.666667      455.555556
IceCream_Sales   455.555556     5666.666667

In [49]:
df.corr()

Temperature  IceCream_Sales
Temperature        1.000000        0.999406
IceCream_Sales     0.999406        1.000000

In [45]:
s=pd.Series([1000,2000,3000,5000,9000])
s

0    1000
1    2000
2    3000
3    5000
4    9000
dtype: int64

# Normalization

In [56]:
s.min()

1000

In [58]:
s.max()

9000

In [62]:
s_norm=(s-s.min())/(s.max()-s.min())
print(s_norm)

0    0.000
1    0.125
2    0.250
3    0.500
4    1.000
dtype: float64


# Import Modules

In [73]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
import pandas as pd

In [75]:
s=pd.Series([1000,2000,3000,5000,9000])
s

0    1000
1    2000
2    3000
3    5000
4    9000
dtype: int64

In [77]:
s_norm=MinMaxScaler().fit_transform(s.values.reshape(-1,1)) #using
print(s_norm)

[[0.   ]
 [0.125]
 [0.25 ]
 [0.5  ]
 [1.   ]]


In [79]:
df=pd.DataFrame({
    "Temp": [20,25,30,35,40],
    "Humidity": [30,45,60,70,90]
})
df

Temp  Humidity
0    20        30
1    25        45
2    30        60
3    35        70
4    40        90

In [81]:
norm_data=MinMaxScaler().fit_transform(df)

In [83]:
norm_data

array([[0.        , 0.        ],
       [0.25      , 0.25      ],
       [0.5       , 0.5       ],
       [0.75      , 0.66666667],
       [1.        , 1.        ]])

In [87]:
norm_df=pd.DataFrame(norm_data,columns=df.columns)
norm_df

Temp  Humidity
0  0.00  0.000000
1  0.25  0.250000
2  0.50  0.500000
3  0.75  0.666667
4  1.00  1.000000

# Standardization

In [90]:
s=pd.Series([1000,2000,3000,5000,9000])
s

0    1000
1    2000
2    3000
3    5000
4    9000
dtype: int64

In [92]:
s.mean()

4000.0

In [94]:
s.std()

3162.2776601683795

In [96]:
Z_Score=(s-s.mean()/s.std())
print(Z_Score)

0     998.735089
1    1998.735089
2    2998.735089
3    4998.735089
4    8998.735089
dtype: float64


In [98]:
Z_Score=StandardScaler().fit_transform(s.values.reshape(-1,1))
print(Z_Score)

[[-1.06066017]
 [-0.70710678]
 [-0.35355339]
 [ 0.35355339]
 [ 1.76776695]]


# Day-10

# Missing Values

In [52]:
import pandas as pd
df=pd.read_csv(r"C:\Users\raidu\Downloads\weather_data.csv")       #Mini Project      
df

DATE       CITy  TEMPERATURE  HUMIDITY CONDITION
0   01-01-1900  HYDERABAD         28.0      60.0     SUNNY
1   02-01-1990  HYDERABAD          NaN      52.0     SUNNY
2   03-01-1990  HYDERABAD         30.0      58.0    CLOUDY
3   04-01-1990  HYDERABAD         31.0       NaN    CLOUDY
4   05-01-1990  HYDERABAD         32.0      57.0    CLOUDY
5   06-01-1990  HYDERABAD         33.0      55.0     SUNNY
6   07-01-1990  BANGALORE          NaN      54.0     SUNNY
7   08-01-1990  BANGALORE         35.0       NaN     SUNNY
8   09-01-1990  BANGALORE          NaN      58.0     SUNNY
9   10-01-1990  BANGALORE         37.0      59.0     SUNNY
10  11-01-1990  BANGALORE         38.0      60.0    CLOUDY
11  12-01-1990  BANGALORE         39.0      61.0    CLOUDY

In [54]:
df.isnull()

DATE   CITy  TEMPERATURE  HUMIDITY  CONDITION
0   False  False        False     False      False
1   False  False         True     False      False
2   False  False        False     False      False
3   False  False        False      True      False
4   False  False        False     False      False
5   False  False        False     False      False
6   False  False         True     False      False
7   False  False        False      True      False
8   False  False         True     False      False
9   False  False        False     False      False
10  False  False        False     False      False
11  False  False        False     False      False

In [56]:
df.isnull().sum()

DATE           0
CITy           0
TEMPERATURE    3
HUMIDITY       2
CONDITION      0
dtype: int64

In [58]:
df_clean=df.dropna()

In [60]:
df_clean

DATE       CITy  TEMPERATURE  HUMIDITY CONDITION
0   01-01-1900  HYDERABAD         28.0      60.0     SUNNY
2   03-01-1990  HYDERABAD         30.0      58.0    CLOUDY
4   05-01-1990  HYDERABAD         32.0      57.0    CLOUDY
5   06-01-1990  HYDERABAD         33.0      55.0     SUNNY
9   10-01-1990  BANGALORE         37.0      59.0     SUNNY
10  11-01-1990  BANGALORE         38.0      60.0    CLOUDY
11  12-01-1990  BANGALORE         39.0      61.0    CLOUDY

In [62]:
df

DATE       CITy  TEMPERATURE  HUMIDITY CONDITION
0   01-01-1900  HYDERABAD         28.0      60.0     SUNNY
1   02-01-1990  HYDERABAD          NaN      52.0     SUNNY
2   03-01-1990  HYDERABAD         30.0      58.0    CLOUDY
3   04-01-1990  HYDERABAD         31.0       NaN    CLOUDY
4   05-01-1990  HYDERABAD         32.0      57.0    CLOUDY
5   06-01-1990  HYDERABAD         33.0      55.0     SUNNY
6   07-01-1990  BANGALORE          NaN      54.0     SUNNY
7   08-01-1990  BANGALORE         35.0       NaN     SUNNY
8   09-01-1990  BANGALORE          NaN      58.0     SUNNY
9   10-01-1990  BANGALORE         37.0      59.0     SUNNY
10  11-01-1990  BANGALORE         38.0      60.0    CLOUDY
11  12-01-1990  BANGALORE         39.0      61.0    CLOUDY

In [64]:
df["TEMPERATURE"]=df["TEMPERATURE"].fillna(12)

In [66]:
df

DATE       CITy  TEMPERATURE  HUMIDITY CONDITION
0   01-01-1900  HYDERABAD         28.0      60.0     SUNNY
1   02-01-1990  HYDERABAD         12.0      52.0     SUNNY
2   03-01-1990  HYDERABAD         30.0      58.0    CLOUDY
3   04-01-1990  HYDERABAD         31.0       NaN    CLOUDY
4   05-01-1990  HYDERABAD         32.0      57.0    CLOUDY
5   06-01-1990  HYDERABAD         33.0      55.0     SUNNY
6   07-01-1990  BANGALORE         12.0      54.0     SUNNY
7   08-01-1990  BANGALORE         35.0       NaN     SUNNY
8   09-01-1990  BANGALORE         12.0      58.0     SUNNY
9   10-01-1990  BANGALORE         37.0      59.0     SUNNY
10  11-01-1990  BANGALORE         38.0      60.0    CLOUDY
11  12-01-1990  BANGALORE         39.0      61.0    CLOUDY

In [68]:
df["TEMPERATURE"]=df["TEMPERATURE"].fillna(df.TEMPERATURE.mean())

In [70]:
df

DATE       CITy  TEMPERATURE  HUMIDITY CONDITION
0   01-01-1900  HYDERABAD         28.0      60.0     SUNNY
1   02-01-1990  HYDERABAD         12.0      52.0     SUNNY
2   03-01-1990  HYDERABAD         30.0      58.0    CLOUDY
3   04-01-1990  HYDERABAD         31.0       NaN    CLOUDY
4   05-01-1990  HYDERABAD         32.0      57.0    CLOUDY
5   06-01-1990  HYDERABAD         33.0      55.0     SUNNY
6   07-01-1990  BANGALORE         12.0      54.0     SUNNY
7   08-01-1990  BANGALORE         35.0       NaN     SUNNY
8   09-01-1990  BANGALORE         12.0      58.0     SUNNY
9   10-01-1990  BANGALORE         37.0      59.0     SUNNY
10  11-01-1990  BANGALORE         38.0      60.0    CLOUDY
11  12-01-1990  BANGALORE         39.0      61.0    CLOUDY

In [76]:
df["HUMIDITY"]=df["HUMIDITY"].fillna(20)

In [78]:
df

DATE       CITy  TEMPERATURE  HUMIDITY CONDITION
0   01-01-1900  HYDERABAD         28.0      60.0     SUNNY
1   02-01-1990  HYDERABAD         12.0      52.0     SUNNY
2   03-01-1990  HYDERABAD         30.0      58.0    CLOUDY
3   04-01-1990  HYDERABAD         31.0      20.0    CLOUDY
4   05-01-1990  HYDERABAD         32.0      57.0    CLOUDY
5   06-01-1990  HYDERABAD         33.0      55.0     SUNNY
6   07-01-1990  BANGALORE         12.0      54.0     SUNNY
7   08-01-1990  BANGALORE         35.0      20.0     SUNNY
8   09-01-1990  BANGALORE         12.0      58.0     SUNNY
9   10-01-1990  BANGALORE         37.0      59.0     SUNNY
10  11-01-1990  BANGALORE         38.0      60.0    CLOUDY
11  12-01-1990  BANGALORE         39.0      61.0    CLOUDY

In [80]:
df["HUMIDITY"]=df["HUMIDITY"].fillna(df.HUMIDITY.mean())

In [82]:
df

DATE       CITy  TEMPERATURE  HUMIDITY CONDITION
0   01-01-1900  HYDERABAD         28.0      60.0     SUNNY
1   02-01-1990  HYDERABAD         12.0      52.0     SUNNY
2   03-01-1990  HYDERABAD         30.0      58.0    CLOUDY
3   04-01-1990  HYDERABAD         31.0      20.0    CLOUDY
4   05-01-1990  HYDERABAD         32.0      57.0    CLOUDY
5   06-01-1990  HYDERABAD         33.0      55.0     SUNNY
6   07-01-1990  BANGALORE         12.0      54.0     SUNNY
7   08-01-1990  BANGALORE         35.0      20.0     SUNNY
8   09-01-1990  BANGALORE         12.0      58.0     SUNNY
9   10-01-1990  BANGALORE         37.0      59.0     SUNNY
10  11-01-1990  BANGALORE         38.0      60.0    CLOUDY
11  12-01-1990  BANGALORE         39.0      61.0    CLOUDY